---

keepTemporaryFiles: False
keepBuggedFiles: True
resultsBaseDir: ./results
#resultsBaseDir: /home/user/results
#oxDNAFolder: ../../oxDNA/
#oxDNAPath: ../../oxDNA/build/bin/oxDNA
#noPeppercornLogFiles: True


batch_mode: False
save_period: 0
min_free_mem_pct: 10.


# Type of experiment
expeType: ME-peppercorn
#nbStages: 1
nbStages: 4

# DNA
#length: 2
#dnaDomains:
#    a: 10
#    b: 10
length: 4
dnaDomains:
    a: 6
    b: 7

# Peppercorn
maxComplexSize: 10
maxComplexCount: 400 # 400
maxReactionCount: 5000 # 2000
concCutOff: 0.5
#sparcity: 0.80
#peppercornDFS: True

# Gillespie
simulationDuration: 3600.0
defaultConc: 0.0000001
maxStrandCount: 10
minSize: 0
maxSize: 30


# Fitness and features
#fitness_type: "medianStruct"
#fitness_type: "meanStruct"
#fitness_type: "entropyComplexSize"
#fitness_type: "nbLoops"
fitness_type: "slope_meanStruct"
#features_list: ["reactionRatio", "structSizeNormalisedStddev"]
#features_list: ["topologicalComplexity", "reactionRatio"]
#features_list: ["nbActive", "reactionRatio"]
#features_list: ["nbActive", "slope_reactionRatio"]
features_list: ["nbActive", "slope_log10ReactionCount", "slope_length"]
#medianStructDomain: [1.0, 100.0]
#meanStructDomain: [1.0, 50.0]
slope_meanStructDomain: [0., 4.0]
slope_reactionRatioDomain: [-50., 50.0]
slope_log10ReactionCountDomain: [0., 0.5]
slope_lengthDomain: [0., 50.0]
entropyComplexSizeDomain: [0.0, 5.0]
nbLoopsDomain: [0, 100]
#topologicalComplexityDomain: [0.0, 1.0]
topologicalComplexityDomain: [0.0, 0.07]
nbActiveDomain: [1, 16]
reactionRatioDomain: [0.0, 1.0]
structSizeNormalisedStddevDomain: [0.0, 0.4]


stage0Config:
    maxComplexSize: 5
    maxComplexCount: 100
    maxReactionCount: 500
    coeff: 1

stage1Config:
    maxComplexSize: 10
    maxComplexCount: 200
    maxReactionCount: 1000
    coeff: 2

stage2Config:
    maxComplexSize: 15
    maxComplexCount: 300
    maxReactionCount: 1500
    coeff: 3

stage3Config:
    maxComplexSize: 20
    maxComplexCount: 400
    maxReactionCount: 2000
    coeff: 4



#main_algorithm_name: algo7
main_algorithm_name: algoArchive
#main_algorithm_name: algoSq1


# The list of all container.
containers:
    cont0:
        type: Grid         # The type of the container (e.g. Grid, CVTGrid, Container, NoveltyArchive, ...)
        name: cont0                              # The name of the container. Optional. Default to the parent key (here also 'cont0')
        shape: [5, 16, 16]                          # The number of bins for each feature
        max_items_per_bin: 1                     # The number of items in each bin of the grid
        #depot_type: True



# The list of all algorithms
algorithms:
    # Default parameter values for each algorithm
    optimisation_task: maximisation   # We perform maximisation of all fitness objectives
    #dimension: 16                     # The number of dimensions of the problem. For rastrigin, any dimension >= 2 can be chosen
    dimension: 256                     # The number of dimensions of the problem. For rastrigin, any dimension >= 2 can be chosen
    ind_domain: [0., 1.]              # The domain of each value of the genome (optional)


    algo1:
        type: RandomSearchMutPolyBounded
        container: cont0
        budget: 30
        batch_size: 10
        init_pb: 0.1
        sel_pb: 0.9
        eta: 20.0
        mut_pb: 0.2


    algo2:
        type: GreyCode
        container: cont0
        budget: 50
        batch_size: 10

    algo3:
        type: SparseBinaryGA
        container: cont0
        budget: 3000
        batch_size: 10
        init_pb: 0.4
        sel_pb: 0.6
        mut_pb: 0.10
        sparsity_domain: [0.10, 0.90]

    algo4:
        type: SparseBinaryGA2
        container: cont0
        budget: 100
        batch_size: 10
        init_pb: 0.4
        sel_pb: 0.6
        mut_pb: 0.10
        sparsity_domain: [0.20, 0.80]
        genome_active_dimension: 256 #16

    algo5:
        type: SparseSobol
        container: cont0
        budget: 30
        batch_size: 10
        #sparsity: 0.99
        #sparsities: [0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]
        #sparsities: [0.80, 0.85, 0.90, 0.95, 0.99]
        sparsities: [0.95]


    algo6:
        type: SparseExhaustive
        container: cont0
        #budget: 1000
        batch_size: 10
        nbActiveList: [2]


    algo7:
        type: SparseExhaustiveMask
        container: cont0
        #budget: 1000
        batch_size: 10
        activeGenesList: [0, 5, 10, 15, 80, 85, 90, 95, 160, 165, 170, 175, 240, 245, 250, 255]

    algoArchive:
        type: FromArchive
        container: cont0
        reference_data_files: ["results/peppercorn30x400x2000-L2-meanStruct-structSizeNormalisedStddev-reactionRatio--Grid50x50--SparseExhausiveMask-65536x64-ooee/final_20190905031726.p"]

#    algoSq1:
#        type: Sq
#        container: cont0
#        #algorithms: ['algo5', 'algo4']
#        algorithms: ['algoArchive', 'algo4']


# MODELINE "{{{1
# vim:expandtab:softtabstop=4:shiftwidth=4:fileencoding=utf-8
# vim:foldmethod=marker
