FROM lcazenille/ubuntupysshgcc

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

RUN \
    apt-get update && \
    apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -yqq graphviz git \
    libtiff5-dev libjpeg-turbo8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev

RUN mkdir -p /home/user

# Download repositories
RUN cd /home/user && git clone https://bitbucket.org/leo-cazenille/kakenhievolvedna.git

RUN pip install --upgrade cython && pip3 install --upgrade cython

RUN apt-get -y install python-tk 
RUN apt-get -y install libgl1-mesa-dev
RUN apt install -y subversion 
RUN apt-get install pkg-config 
RUN apt install -y gcc 
RUN apt-get -y install \
    clang \
    clang-format \
    make \
    cmake

# Install peppercorn
RUN \
    pip3 install vtk pybind11 pyvista tqdm colorama psutil parse powerlaw networkx matplotlib==2.2.4 seaborn graphviz pydot && \
    pip3 install qdpy==0.1.0 && \
    #    pip3 install -U qdpy==0.1.0 && \
    pip install mpmath==0.19 numpy scipy sympy==1.2 networkx matplotlib==2.2.4 && \
    git clone https://github.com/leo-cazenille/peppercornenumerator.git && \ 
    cd /peppercornenumerator && python2 setup.py install

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib/python3.7/dist-packages/vtk
#RUN \
#    pip3 install -U -r /home/user/kakenhievolvedna/requirements.tx

# Install nupack
COPY nupack3.2.2.tar.gz /
RUN \
    tar xvf nupack3.2.2.tar.gz && \
    cd nupack3.2.2 && \
    mkdir build && cd build && \
    cmake .. && make -j 20 && \
    make install


# Prepare for entrypoint execution
#CMD ["/bin/bash"]

ENTRYPOINT cd /home/user/kakenhievolvedna/oxdna_run ; /usr/bin/python3.7 -u /home/user/kakenhievolvedna/oxdna_run/main.py
# ENTRYPOINT cd /home/user/kakenhievolvedna2 ; ./scripts/runAllExpes.sh


#CMD ["1000", "normal"]

# MODELINE	"{{{1
# vim:expandtab:softtabstop=4:shiftwidth=4:fileencoding=utf-8
# vim:foldmethod=marker

#コンテナから出ても継続されるようにentrypointを設定する。コンテナには入らない