FROM ubuntu:22.04
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y libbz2-dev
RUN apt -y install libssl-dev libffi-dev
RUN apt-get install xz-utils

RUN \
    apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -yqq graphviz git \
    libtiff5-dev libjpeg-turbo8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev

RUN mkdir -p /home/user

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN echo "Asia/Tokyo" > /etc/timezone
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
# RUN apt install -y python3-pip --fix-missing
# RUN apt-get -y install libjpeg-dev
# RUN apt -y install libjpeg-dev
RUN apt-get -y install python-tk 
# RUN apt-get -y install libgl1-mesa-dev
RUN apt install -y subversion 
RUN apt-get install pkg-config 
RUN apt install -y gcc 
RUN apt-get -y install \
    clang \
    clang-format \
    make \
    cmake


RUN wget https://www.python.org/ftp/python/3.9.2/Python-3.9.2.tar.xz && tar xJf Python-3.9.2.tar.xz
RUN cd Python-3.9.2 && ./configure && make && make install



# Install peppercorn
RUN python3.9 -m pip install --upgrade pip
RUN pip3 install vtk pybind11 tqdm colorama psutil textfile
RUN pip3 install parse powerlaw networkx 
#RUN pip3 install matplotlib==2.2.4 seaborn graphviz pydot
RUN pip3 install matplotlib seaborn graphviz pydot
#RUN pip3 install mpmath==0.19 numpy scipy sympy==1.2
RUN pip3 install mpmath numpy scipy sympy
RUN git clone https://github.com/leo-cazenille/peppercornenumerator.git
# RUN pip3 install -U sklearn
RUN pip3 install -U scikit-learn
#RUN pip3 install pyvista

#pip3 for qdpy
#RUN pip3 install -U qdpy==0.1.2.1
RUN pip3 --no-cache-dir install -U numpy pandas tqdm git+https://gitlab.com/leo.cazenille/qdpy.git@develop
#RUN pip install -U pip setuptools
RUN apt update; apt install -y python2.7
RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
RUN python2 get-pip.py
RUN python2 -m pip install setuptools
RUN python2 -m pip install networkx==2.2 pyparsing mpmath==0.19 numpy scipy sympy==1.2 matplotlib==2.2.4
RUN cd /peppercornenumerator && python2 setup.py install

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib/python3.9/dist-packages/vtk

ENTRYPOINT home/user/kakenhievolvedna2/revive_peppercorn_pil.sh